spring:
  jpa:
    open-in-view: false
  flyway:
    enabled: false

---
spring.config.activate.on-profile: local

spring:
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/seed/local
    baseline-on-migrate: true
    baseline-version: 12
    baseline-description: manual_schema_before_flyway

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring.config.activate.on-profile: qa

spring:
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 12
    baseline-description: manual_schema_before_flyway

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring.config.activate.on-profile: prod

spring:
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring.config.activate.on-profile: test
