springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    persist-authorization: true
    path: /api/nuntteo/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    disable-swagger-default-url: true
  show-actuator: true
  api-docs:
    path: /api/nuntteo/v3/api-docs

swagger.server.url: ${SWAGGER_SERVER_URL}

---
spring.config.activate.on-profile: "local"


---
spring.config.activate.on-profile: "dev"


---
spring.config.activate.on-profile: "prod"


---
spring.config.activate.on-profile: "test"

