name: CI - Build & Test


on:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 리포지토리 소스 코드 체크아웃
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Java 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 캐시 설정 (빌드 속도 개선)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle Wrapper 실행 권한 부여
      - name: Grant execute permission
        run: chmod +x ./gradlew

      # 5. 테스트 실행
#      - name: Run tests
#        run: ./gradlew test --no-daemon

      # 6. env.properties 생성 (JAR 외부에 생성해 보안 취약점 예방)
      - name: Generate env.properties
        run: |
          mkdir -p /tmp/config
          printf "%s" "${{ secrets.DEV_ENV_PROPERTIES }}" > tmp/config/env.properties

      # 7. 빌드
      - name: Build JAR
        run: ./gradlew bootJar --no-daemon
